name: run-on-pull-request-closed
on: pull_request

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"